In [1]:
import torch

In [2]:
x = torch.ones(3,3,requires_grad=True)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)

In [4]:
y = x +2
print(y)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]], grad_fn=<AddBackward0>)


In [5]:
y.grad_fn

In [6]:
z = y * y * 3
out = z.mean()

print(z, out)

(tensor([[27., 27., 27.],
        [27., 27., 27.],
        [27., 27., 27.]], grad_fn=<MulBackward0>), tensor(27., grad_fn=<MeanBackward0>))


In [7]:
a = torch.randn(2,2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
print(a.grad_fn)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
None
True


In [8]:
out.backward()
print(x.grad)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [9]:
x = torch.randn(3, requires_grad=True)
y = x * 2

while y.data.norm() < 1000:
    y = y*2
print(y)

tensor([  940.7378,   -25.7085, -1002.7584], grad_fn=<MulBackward0>)


In [11]:
v = torch.tensor([0.1, 1.0, 0.00001],dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-02])
