In [2]:
from __future__ import print_function
import torch
torch.__version__
import numpy as np

In [3]:
x = torch.empty(3,3)
x

tensor([[4.5183e+07, 4.5688e-41, 4.5183e+07],
        [4.5688e-41,        nan, 0.0000e+00],
        [1.1578e+27, 4.1666e+34, 6.7262e-44]])

In [4]:
x = torch.rand(3,3)
x

tensor([[0.4061, 0.8959, 0.5876],
        [0.5736, 0.2626, 0.8860],
        [0.5454, 0.3355, 0.7868]])

In [6]:
x = torch.zeros(3,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [8]:
import numpy as np
x = np.array([1.3,4,5.2])
print(x)
x = torch.tensor(x)
print(x)

[1.3 4.  5.2]
tensor([1.3000, 4.0000, 5.2000], dtype=torch.float64)


In [9]:
x = torch.ones(4,4,dtype=torch.double)
print(x)
x = torch.rand_like(x,dtype=torch.float)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)
tensor([[0.8617, 0.8313, 0.3992, 0.1177],
        [0.3335, 0.9675, 0.7219, 0.5863],
        [0.6942, 0.5695, 0.0622, 0.0514],
        [0.1344, 0.3363, 0.0098, 0.1779]])


In [11]:
print(x.size())

torch.Size([4, 4])


In [15]:
y = torch.ones_like(x)
print(x+y)
print(torch.add(x,y))
print(y.add(x))
print(y)
print(y.add_(x)) #in_place function may change the variable itself
y

tensor([[1.8617, 1.8313, 1.3992, 1.1177],
        [1.3335, 1.9675, 1.7219, 1.5863],
        [1.6942, 1.5695, 1.0622, 1.0514],
        [1.1344, 1.3363, 1.0098, 1.1779]])
tensor([[1.8617, 1.8313, 1.3992, 1.1177],
        [1.3335, 1.9675, 1.7219, 1.5863],
        [1.6942, 1.5695, 1.0622, 1.0514],
        [1.1344, 1.3363, 1.0098, 1.1779]])
tensor([[1.8617, 1.8313, 1.3992, 1.1177],
        [1.3335, 1.9675, 1.7219, 1.5863],
        [1.6942, 1.5695, 1.0622, 1.0514],
        [1.1344, 1.3363, 1.0098, 1.1779]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1.8617, 1.8313, 1.3992, 1.1177],
        [1.3335, 1.9675, 1.7219, 1.5863],
        [1.6942, 1.5695, 1.0622, 1.0514],
        [1.1344, 1.3363, 1.0098, 1.1779]])


tensor([[1.8617, 1.8313, 1.3992, 1.1177],
        [1.3335, 1.9675, 1.7219, 1.5863],
        [1.6942, 1.5695, 1.0622, 1.0514],
        [1.1344, 1.3363, 1.0098, 1.1779]])

In [16]:
x = torch.rand(4,4)
y = x.view(-1)
z = x.view(-1,8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [22]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.5957])
-0.595709562302


In [23]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])

In [26]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [27]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [30]:
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)
np.add(a,1,out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [32]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    x = torch.ones(3)
    y = torch.ones_like(x,device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to('cpu',torch.float))

RuntimeError: CUDA error: out of memory